MONGODB_HOST = 'sunghopark.info'
MONGODB_PORT = 27017
MONGODB_DB = 'chicago_dev'
MONGODB_COLL = 'locs'
MAX_NUM_SEARCH_RESULTS = 25
MONGODB_MIN_DISTANCE_FIELD_NAME = 'md'
MONGODB_MIN_DISTANCE_FACILITY_FIELD_NAME = 'mdfn'

_ID_KEY = '_id'
X_KEY = 'x'
Y_KEY = 'y'
NON_FACILITY_KEYS = [_ID_KEY, X_KEY, Y_KEY]

NUM_CRITERIA = 5
POSSIBLE_DISTANCE_OPTIONS = [0.1, 0.2, 0.5, 1.0]  # unit: miles
NULL_STRING = 'null'
NO_RESULT_FOUND_MSG = 'No result found.'